version: 2.1

jobs:
  rustfmt:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Install cargo fmt
          command: rustup component add rustfmt
      - run:
          name: Run Rust formatter
          command: cargo fmt --all -- --check

workflows:
  version: 2
  build_and_test:
    jobs:
      - rustfmt
